// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace StoreApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231216155322_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductName = "Kalem",
                            ProductPrice = 11m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductName = "Silgi",
                            ProductPrice = 10m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductName = "Defter",
                            ProductPrice = 30m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductName = "Kitap",
                            ProductPrice = 100m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductName = "Sözlük",
                            ProductPrice = 79m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
